---
  # Thanks to https://medium.com/hackernoon/setup-docker-swarm-on-aws-using-ansible-terraform-daa1eabbc27d
  - name: Init Swarm Manager
    hosts: managers
    gather_facts: False
    remote_user: ubuntu
    vars:
      ansible_host_key_checking: false

    tasks:
      - name: Swarm Init
        command: docker swarm init --advertise-addr {{ inventory_hostname }}
        ignore_errors: true

      - name: Get Worker Token
        command: docker swarm join-token worker -q
        register: worker_token

      - name: Show Worker Token
        debug: var=worker_token.stdout

      - name: Manager Token
        command: docker swarm join-token manager -q
        register: manager_token

      - name: Show Manager Token
        debug: var=manager_token.stdout
      
      - name: Create core overlay network
        command: docker network create --driver=overlay --attachable core
        ignore_errors: true


      - name: Create socket proxy overlay network
        command: docker network create --driver overlay --scope swarm --opt encrypted --attachable cloud-socket-proxy
        ignore_errors: true
      
      - name: Copy github key
        copy:
          src: ./github-infra-swarm-key
          dest: ~/.ssh/id_ed25519
          owner: ubuntu
          group: ubuntu
          mode: '0600'

      - name: Check existence of git repo
        stat:
          path: ~/infra-swarm
        register: git_dir
      - name: Add github SSH key to known hosts
        command: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        when: not git_dir.stat.exists
      - name: Clone stack deployment repo 
        command: git clone git@github.com:ReSource-Network/infra-swarm.git ~/infra-swarm
        when: not git_dir.stat.exists

      
      # docker stack deploy -c traefik.yml proxy

  - name: Join Swarm Cluster
    hosts: workers
    remote_user: ubuntu
    gather_facts: False
    vars:
      token: "{{ hostvars[groups['managers'][0]]['worker_token']['stdout'] }}"
      manager: "{{ hostvars[groups['managers'][0]]['inventory_hostname'] }}"
      ansible_host_key_checking: false
    tasks:
      - name: Join Swarm Cluster as a Worker
        command: docker swarm join --token {{ token }} {{ manager }}:2377
        register: worker

      - name: Show Results
        debug: var=worker.stdout

      - name: Show Errors
        debug: var=worker.stderr
