---
  # Thanks to https://medium.com/hackernoon/setup-docker-swarm-on-aws-using-ansible-terraform-daa1eabbc27d
  - name: Init Swarm Manager
    hosts: managers
    gather_facts: False
    remote_user: ubuntu
    vars:
      ansible_host_key_checking: false

    tasks:
      - name: Swarm Init
        command: docker swarm init --advertise-addr {{ inventory_hostname }}

      - name: Get Worker Token
        command: docker swarm join-token worker -q
        register: worker_token

      - name: Show Worker Token
        debug: var=worker_token.stdout

      - name: Manager Token
        command: docker swarm join-token manager -q
        register: manager_token

      - name: Show Manager Token
        debug: var=manager_token.stdout

  - name: Join Swarm Cluster
    hosts: workers
    remote_user: ubuntu
    gather_facts: False
    vars:
      token: "{{ hostvars[groups['managers'][0]]['worker_token']['stdout'] }}"
      manager: "{{ hostvars[groups['managers'][0]]['inventory_hostname'] }}"
      ansible_host_key_checking: false
    tasks:
      - name: Join Swarm Cluster as a Worker
        command: docker swarm join --token {{ token }} {{ manager }}:2377
        register: worker

      - name: Show Results
        debug: var=worker.stdout

      - name: Show Errors
        debug: var=worker.stderr
