version: '3.9'
services:
  whoami:
    image: "traefik/whoami"
    ports:
      - 9090:80
    networks:
      - core
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Method(`GET`)" #Host(`test.rsrc.co`)"
        - "traefik.http.routers.whoami.entrypoints=web"
        # - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
  core:
    external: true
