import { writeFileSync } from "fs";
const [stackName] = process.argv.slice(2);
const stackData = require("../tmp/stack-output.json");

function hostsTemplate(managers: string[], workers: string[]) {
  return `
# This file is managed by CDK for Terraform.
# Any changes will be overwritten.

# This file is generated by cdktf.
#
[managers]
${managers.join("\n")}

[workers]
${workers.join("\n")}
`;
}

///////////////////////////
if (!stackName) {
  console.error("Usage: yarn write-hosts-file <stack-name>");
  process.exit(1);
}

console.log(`Writing hosts file for ${stackName}.`);

// console.log(stackData);

const worker_addresses = [];
const manager_addresses = [];
for (let name in stackData[stackName]) {
  if (name.match(/^manager.*_public_ip/)) {
    manager_addresses.push(stackData[stackName][name]);
  }
  if (name.match(/^worker\d+_public_ip/)) {
    worker_addresses.push(stackData[stackName][name]);
  }
}

console.log(`Managers: ${manager_addresses.join(", ")}`);
console.log(`Workers: ${worker_addresses.join(", ")}`);

const hostsFile = hostsTemplate(manager_addresses, worker_addresses);
writeFileSync("hosts", hostsFile);
