import { writeFileSync } from "fs";
import { open } from "fs/promises";
// const stackData = require("../cdktf.out/stacks/aws_instance/cdk.tf.json");
const stackData = require("../tmp/stack-output.json");

function hostsTemplate(managers: string[], workers: string[]) {
  return `
# This file is managed by CDK for Terraform.
# Any changes will be overwritten.

# This file is generated by cdktf.
#
[managers]
${managers.join("\n")}

[workers]
${workers.join("\n")}
  `;
}

const hostsFile = hostsTemplate(
  [stackData.aws_instance.manager_public_ip],
  [
    stackData.aws_instance.worker0_public_ip,
    stackData.aws_instance.worker1_public_ip,
  ]
);
writeFileSync("hosts", hostsFile);
